-- AlterEnum
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'PROGRESS_OFFICER';

-- AlterEnum
ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'EMPLOYEES_VIEW';
ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'PAYROLL_VIEW';
ALTER TYPE "Permission" ADD VALUE IF NOT EXISTS 'INCENTIVES_VIEW';
