import { AppointmentLetterLanguage } from '@prisma/client';
import {
  appointmentFamilyMeta,
  type AppointmentSopFamily,
} from './appointment-families';

const SOP_EN: Record<AppointmentSopFamily, string[]> = {
  MEDICAL: [
    'Protect patient confidentiality and medical records. Do not disclose clinical information except to authorized persons under YCDO policy.',
    'Do not refer YCDO patients to a personal clinic, private hospital, or private clinic except an approved or necessary referral under YCDO policy.',
    'Do not give a personal visiting card or private commercial contact details to divert YCDO patients.',
    'Prescriptions, tests, and referrals must follow YCDO clinical SOPs.',
    'Do not deal with medical representatives or suppliers except as authorized under YCDO policy. Personal benefit is prohibited.',
    'Record diagnosis, prescription, treatment, investigation, and follow-up accurately and on time.',
    'Report emergencies, adverse events, medication errors, and patient-safety concerns immediately through the authorized channel.',
    'Use applicable HMS, Laboratory, Pharmacy, and Medicine Management systems according to your role.',
    'Uphold patient dignity, safety, and authorized clinical practice only.',
  ],
  PHARMACY_MEDICINE: [
    'Maintain complete medicine issue, receipt, stock, and return records.',
    'Do not move stock without an authorized record and approval.',
    'Record batch, expiry, quantity, and stock movement accurately.',
    'Handle expired, damaged, returned, and restricted medicines only under approved SOP.',
    'Do not make unauthorized stock adjustments, manipulation, or concealment.',
    'Use Medicine Management / Pharmacy systems as mandatory for applicable transactions.',
    'Issue medicine only under an approved prescription, instruction, or SOP.',
    'Do not engage in unauthorized medical-representative or supplier dealings, or take personal benefit.',
    'Complete stock audit, reconciliation, and handover as required.',
    'Report shortages, excess, expiry risk, and suspicious transactions immediately.',
    'Pharmacy reception must follow the approved token, receipt, payment, and workflow.',
    'An Audit Officer must report discrepancies and must not conceal them.',
  ],
  LABORATORY: [
    'Verify sample, test request, and patient identity before collection or processing.',
    'Follow SOP for sample collection, labeling, storage, transport, processing, and disposal.',
    'Do not modify, substitute, fabricate, or conceal samples or results without authorization.',
    'Result entry, verification, and release may be performed only by authorized personnel.',
    'Protect laboratory and patient confidentiality.',
    'Use the Laboratory Management System and prescribed registers.',
    'Maintain reagent, kit, and consumable stock records.',
    'Handle expired, damaged, or contaminated material under approved SOP.',
    'Report equipment, calibration, sample-rejection, and contamination issues immediately.',
    'Unauthorized disclosure of results is prohibited.',
    'Complete audit, reconciliation, and handover as required.',
    'Observe infection-control and biohazard precautions.',
    'Do not conceal discrepancies or errors.',
  ],
  SURGICAL_RADIOLOGY: [
    'Verify patient identity and the intended procedure before any intervention or imaging.',
    'Follow OT sterility, infection-control, and surgical checklist requirements applicable to your role.',
    'Account for instruments, equipment, and consumables; report loss, damage, or shortage immediately.',
    'Document patient preparation, transfer, handover, and recovery as required.',
    'For radiology roles, complete patient, imaging, procedure, and radiation-safety checks.',
    'Do not alter images or reports without authorization.',
    'Protect patient and imaging confidentiality.',
    'Report equipment, calibration, and safety incidents immediately.',
    'Do not perform unauthorized surgical or radiological procedures.',
    'Use applicable HMS, Surgical, Radiology, and Laboratory systems according to your role.',
    'Follow sterilization, waste, and sharps safety rules.',
    'Escalate adverse events, wrong-patient or wrong-site incidents, and equipment failure without delay.',
  ],
  ADMIN_HR_ACCOUNTS: [
    'Keep administrative, HR, and financial records accurate and complete.',
    'Protect confidentiality of employee, financial, and organizational information.',
    'Do not make unauthorized changes to attendance, payroll, stipend, leave, approval, financial, or official documents.',
    'Use HRMS, financial, and reporting systems according to your role.',
    'Act only within delegated authority limits.',
    'Follow HR SOPs for onboarding, attendance, leave, discipline, transfer, and status changes where applicable.',
    'For accounts roles, process receipts, payments, stipend, recovery, and reconciliation according to SOP.',
    'Report discrepancy, duplicate payment, or misuse immediately.',
    'Support branch and department operations and official communication as assigned.',
    'Protect employee personal data.',
    'Cooperate with audit, inquiry, and compliance activity.',
    'Conflict of interest and personal benefit are prohibited.',
    'Protect credentials and access rights.',
    'Concealment of fraud, data breach, or irregularity is itself a violation.',
  ],
  IT_SOFTWARE_MEDIA: [
    'Use systems, software, devices, networks, servers, and databases for official purposes only.',
    'Do not make unauthorized production, database, server, source, or configuration changes.',
    'Protect passwords, API keys, and access tokens.',
    'Keep source code, data, and patient, employee, and financial information confidential.',
    'Follow backup, security, access-control, documentation, and incident SOPs.',
    'Report security, data-loss, malware, and unauthorized-access incidents immediately.',
    'Do not transfer data to personal devices, cloud, USB, or third parties without approval.',
    'YCDO digital assets, source code, and documentation remain organizational property unless formally agreed otherwise.',
    'Access and permissions require approved authorization.',
    'Observe testing, development, and production controls.',
    'Media content may be produced only for an authorized organizational purpose.',
    'Do not publish patient, employee, or beneficiary images, video, or data without authorization.',
    'Do not make unauthorized public statements or disclose confidential information.',
    'Protect assigned media and IT assets.',
    'On transfer or separation, complete handover of access, files, devices, and source materials.',
  ],
  SUPPORT_TECHNICAL: [
    'Protect assigned areas, tools, equipment, biomedical devices, and facilities.',
    'Carry out repairs, installation, or maintenance only under authorized instructions and safety SOPs.',
    'Report electrical, plumbing, biomedical, mechanical, or structural hazards immediately.',
    'Do not use, remove, or take tools, parts, material, or assets for personal or unauthorized purposes.',
    'Keep technical repair, fault, parts, calibration, and handover records as required.',
    'Biomedical equipment must be handled according to manufacturer guidance and YCDO SOP; do not bypass safety locks or calibration controls.',
    'Observe occupational safety rules, including electrical and workshop precautions.',
    'Do not abandon assigned event, emergency, or campaign duty.',
    'Unauthorized absence, negligence, or safety violation may result in disciplinary action under applicable YCDO rules.',
  ],
  SUPPORT_GRADE4: [
    'Protect assigned posts, areas, equipment, and facilities.',
    'Follow duty-area, shift, cleanliness, and movement instructions issued by Branch Management.',
    'Housekeeping and sweeper duties must follow hygiene, waste, and infection-control SOP.',
    'Security duties require remaining at the assigned post, checking unauthorized entry, and reporting incidents immediately.',
    'Lift operators must follow lift safety procedures and must not overload or leave the lift unattended while in use.',
    'Loaders may move material only under authorization and must not damage stock or equipment.',
    'Do not abandon assigned event, emergency, or campaign duty.',
    'Unauthorized absence, negligence, or safety violation may result in disciplinary action under applicable YCDO rules.',
  ],
  SUPPORT_OPERATIONS: [
    'Protect assigned areas, tools, equipment, stock, and facilities.',
    'Follow duty-area, shift, cleanliness, and movement instructions issued by Branch Management.',
    'Kitchen staff must follow hygiene, storage, preparation, serving, and food-safety SOP.',
    'Report kitchen stock or equipment shortage and damage immediately.',
    'Sanitary duties must follow hygiene, waste, and infection-control SOP.',
    'Riders must transport assigned items only on the approved route, protect samples or supplies, and must not tamper with contents.',
    'Do not abandon assigned event, emergency, or campaign duty.',
    'Unauthorized absence, negligence, or safety violation may result in disciplinary action under applicable YCDO rules.',
  ],
  VTI: [
    'Conduct yourself professionally and respectfully with trainees and students.',
    'Follow the approved curriculum, timetable, lesson plan, and practical activity.',
    'Maintain attendance, progress, and assessment records accurately.',
    'Harassment, discrimination, and inappropriate dealing are prohibited.',
    'Use training tools, machines, materials, and cosmetics safely.',
    'Beautician practical work must follow hygiene and sanitation SOP.',
    'Stitching work must follow machine, needle, cutting, and electrical safety rules.',
    'Promote discipline, punctuality, and cleanliness.',
    'Work under principal / incharge oversight as assigned.',
    'Report complaints, safety issues, misconduct, and equipment damage immediately.',
    'Do not manipulate certificates, attendance, assessment, or stock records.',
    'Participate in VTI events, exhibitions, and training programs when formally called.',
    'Protect trainee data confidentiality.',
    'Complete proper handover on transfer or separation.',
    'Repeated negligence, absence, record manipulation, or SOP violation may result in disciplinary action under applicable YCDO rules.',
  ],
};

const SOP_UR: Record<AppointmentSopFamily, string[]> = {
  MEDICAL: [
    'مریض کی رازداری اور میڈیکل ریکارڈ کی حفاظت لازم ہے۔ YCDO پالیسی کے تحت مجاز افراد کے سوا طبی معلومات ظاہر نہ کی جائیں۔',
    'YCDO کے مریضوں کو ذاتی کلینک، پرائیویٹ ہسپتال یا پرائیویٹ کلینک کی طرف رجوع نہ کیا جائے، سوائے منظور شدہ یا ناگزیر ریفرل کے جو YCDO پالیسی کے مطابق ہو۔',
    'YCDO کے مریضوں کو موڑنے کے لیے ذاتی وزٹنگ کارڈ یا پرائیویٹ کاروباری رابطہ نہ دیا جائے۔',
    'نسخے، ٹیسٹ اور ریفرلز YCDO کے کلینیکل SOP کے مطابق ہوں۔',
    'میڈیکل نمائندوں / سپلائرز سے غیر مجاز لین دین منع ہے۔ ذاتی فائدہ حرام ہے۔',
    'تشخیص، نسخہ، علاج، تحقیقات اور فالو اپ درست اور بروقت درج کیے جائیں۔',
    'ایمرجنسی، ناگوار واقعات، ادویاتی غلطی اور مریض کی حفاظت سے متعلق معاملات فوری مجاز چینل پر رپورٹ کیے جائیں۔',
    'اپنے عہدے کے مطابق HMS، لیبارٹری، فارمیسی اور میڈیسن مینجمنٹ سسٹم استعمال کیے جائیں۔',
    'مریض کی عزت، حفاظت اور صرف مجاز کلینیکل پریکٹس لازم ہے۔',
  ],
  PHARMACY_MEDICINE: [
    'ادویات کی اجراء، وصولی، اسٹاک اور واپسی کا مکمل ریکارڈ رکھا جائے۔',
    'بغیر مجاز ریکارڈ / منظوری کے اسٹاک نہ ہلایا جائے۔',
    'بیچ، ایکسپائری، مقدار اور اسٹاک کی نقل و حرکت درست درج ہو۔',
    'ایکسپائر، خراب، واپس یا ممنوع ادویات صرف منظور شدہ SOP کے تحت ہینڈل کی جائیں۔',
    'غیر مجاز اسٹاک ایڈجسٹمنٹ، چھیڑ چھاڑ یا چھپانا منع ہے۔',
    'متعلقہ لین دین کے لیے میڈیسن مینجمنٹ / فارمیسی سسٹم لازمی استعمال ہو۔',
    'ادویات صرف منظور شدہ نسخہ، ہدایت یا SOP کے تحت جاری کی جائیں۔',
    'میڈیکل نمائندے / سپلائر سے غیر مجاز تعلق یا ذاتی فائدہ منع ہے۔',
    'اسٹاک آڈٹ، تطبیق اور ہینڈ اوور حسبِ ہدایت مکمل کیا جائے۔',
    'کمی، زیادتی، ایکسپائری کا خطرہ اور مشکوک لین دین فوری رپورٹ ہوں۔',
    'فارمیسی ریسپشن منظور شدہ ٹوکن، رسید، ادائیگی اور ورک فلو پر چلے۔',
    'آڈٹ آفیسر کو تضادات رپورٹ کرنا ہوں گے؛ چھپانا خود خلاف ورزی ہے۔',
  ],
  LABORATORY: [
    'نمونہ، ٹیسٹ درخواست اور مریض کی شناخت تصدیق کے بغیر کارروائی نہ کی جائے۔',
    'نمونہ لینے، لیبل، ذخیرہ، نقل، پروسیس اور تلفی کا SOP لازمی ہے۔',
    'غیر مجاز طور پر نمونہ یا رپورٹ میں ترمیم، تبدیلی، جعل سازی یا چھپانا منع ہے۔',
    'نتیجہ داخلہ، تصدیق اور اجرا صرف مجاز عملہ کرے۔',
    'لیبارٹری اور مریض کی رازداری قائم رکھیں۔',
    'Laboratory Management System اور مقررہ رجسٹرز استعمال ہوں۔',
    'ری ایجنٹ، کٹ اور کنزیومیبل کا اسٹاک ریکارڈ رکھا جائے۔',
    'ایکسپائر، خراب یا آلودہ مواد منظور شدہ SOP کے تحت ہینڈل ہو۔',
    'آلات، کیلیبریشن، نمونہ مسترد ہونے اور آلودگی فوری رپورٹ ہوں۔',
    'نتائج کی غیر مجاز اشاعت منع ہے۔',
    'آڈٹ، تطبیق اور ہینڈ اوور حسبِ ضرورت مکمل ہوں۔',
    'انفیکشن کنٹرول اور بایو ہیزرڈ احتیاط لازمی ہے۔',
    'غلطی یا تضاد چھپانا منع ہے۔',
  ],
  SURGICAL_RADIOLOGY: [
    'کسی مداخلت یا امیجنگ سے پہلے مریض کی شناخت اور مطلوبہ پروسیجر کی تصدیق کی جائے۔',
    'OT کی صفائی، انفیکشن کنٹرول اور سرجیکل چیک لسٹ اپنے عہدے کے مطابق لاگو ہوں۔',
    'آلات، سامان اور کنزیومیبل کا حساب رکھا جائے؛ گمشدگی، نقصان یا کمی فوری رپورٹ ہو۔',
    'مریض کی تیاری، منتقلی، ہینڈ اوور اور ریکوری حسبِ ہدایت درج ہو۔',
    'ریڈیالوجی کے عہدوں پر مریض، امیجنگ، پروسیجر اور ریڈی ایشن سیفٹی چیکس مکمل ہوں۔',
    'غیر مجاز تصویر یا رپورٹ میں تبدیلی منع ہے۔',
    'مریض اور امیجنگ کی رازداری قائم رکھیں۔',
    'آلات، کیلیبریشن اور حفاظتی واقعات فوری رپورٹ ہوں۔',
    'غیر مجاز سرجیکل یا ریڈیالوجیکل پروسیجر منع ہے۔',
    'اپنے عہدے کے مطابق HMS، سرجیکل، ریڈیالوجی اور لیبارٹری سسٹم استعمال ہوں۔',
    'نس بندی، ویسٹ اور شارپس سیفٹی کے اصولوں پر عمل ہو۔',
    'ناگوار واقعہ، غلط مریض / غلط مقام اور آلات کی خرابی بلا تاخیر آگے بڑھائی جائے۔',
  ],
  ADMIN_HR_ACCOUNTS: [
    'انتظامی، HR اور مالی ریکارڈ درست اور مکمل رکھیں۔',
    'ملازم، مالی اور ادارہ جاتی معلومات کی رازداری قائم رکھیں۔',
    'حاضری، پے رول، وظیفہ، چھٹی، منظوری، مالی یا دفتری دستاویزات میں غیر مجاز تبدیلی منع ہے۔',
    'اپنے عہدے کے مطابق HRMS، مالی اور رپورٹنگ سسٹم استعمال ہوں۔',
    'صرف تفویض شدہ اختیارات کی حد میں کام کریں۔',
    'جہاں لاگو ہو، آن بورڈنگ، حاضری، چھٹی، ڈسپلن، ٹرانسفر اور سٹیٹس کے HR SOP پر عمل ہو۔',
    'اکاؤنٹس کے عہدوں پر رسید، ادائیگی، وظیفہ، وصولی اور تطبیق SOP کے مطابق ہو۔',
    'تضاد، دوہری ادائیگی یا غلط استعمال فوری رپورٹ ہو۔',
    'برانچ / شعبہ کے دفتری کام اور رسمی مراسلت میں تعاون کریں۔',
    'ملازم کے ذاتی ڈیٹا کی حفاظت لازم ہے۔',
    'آڈٹ، انکوائری اور کمپلائنس میں تعاون کریں۔',
    'مفادات کا تصادم اور ذاتی فائدہ منع ہے۔',
    'پاس ورڈز اور رسائی کے حقوق محفوظ رکھیں۔',
    'فراڈ، ڈیٹا بریچ یا بے ضابطگی چھپانا خود خلاف ورزی ہے۔',
  ],
  IT_SOFTWARE_MEDIA: [
    'سسٹمز، سافٹ ویئر، ڈیوائسز، نیٹ ورک، سرورز اور ڈیٹا بیس صرف دفتری استعمال کے لیے ہیں۔',
    'پروڈکشن، ڈیٹا بیس، سرور، سورس یا کنفیگریشن میں غیر مجاز تبدیلی منع ہے۔',
    'پاس ورڈز، API keys اور ایکسیس ٹوکن محفوظ رکھیں۔',
    'سورس کوڈ، ڈیٹا اور مریض / ملازم / مالی معلومات کی رازداری لازم ہے۔',
    'بیک اپ، سیکیورٹی، ایکسیس کنٹرول، دستاویزات اور واقعہ SOP پر عمل ہو۔',
    'سیکیورٹی، ڈیٹا نقصان، مالویئر اور غیر مجاز رسائی فوری رپورٹ ہوں۔',
    'بغیر منظوری ذاتی ڈیوائس، کلاؤڈ، USB یا تیسری پارٹی کو ڈیٹا منتقل نہ کیا جائے۔',
    'YCDO کے ڈیجیٹل اثاثے، سورس کوڈ اور دستاویزات ادارے کی ملکیت ہیں جب تک باضابطہ اتفاق نہ ہو۔',
    'رسائی اور اجازت صرف منظور شدہ اختیار سے ملے۔',
    'ٹیسٹنگ، ڈیولپمنٹ اور پروڈکشن کنٹرولز کا احترام ہو۔',
    'میڈیا مواد صرف مجاز ادارہ جاتی مقصد کے لیے تیار ہو۔',
    'مریض، ملازم یا مستفید کی تصویر، ویڈیو یا ڈیٹا بغیر اجازت شائع نہ ہو۔',
    'غیر مجاز عوامی بیان یا خفیہ انکشاف منع ہے۔',
    'تفویض شدہ میڈیا / IT اثاثے محفوظ رکھیں۔',
    'ٹرانسفر یا علیحدگی پر ایکسیس، فائلز، ڈیوائسز اور سورس کا مکمل ہینڈ اوور لازمی ہے۔',
  ],
  SUPPORT_TECHNICAL: [
    'تفویض شدہ جگہ، اوزار، آلات، بایو میڈیکل ڈیوائسز اور سہولیات کی حفاظت کریں۔',
    'مرمت، تنصیب یا مینٹیننس صرف مجاز ہدایات اور حفاظتی SOP کے تحت ہو۔',
    'برقی، پلمبنگ، بایو میڈیکل، مکینیکل یا ڈھانچے کے خطرات فوری رپورٹ ہوں۔',
    'اوزار، پرزے، سامان یا اثاثے ذاتی یا غیر مجاز استعمال / لے جانے منع ہیں۔',
    'تکنیکی مرمت، خرابی، پرزے، کیلیبریشن اور ہینڈ اوور کا ریکارڈ حسبِ ضرورت رکھا جائے۔',
    'بایو میڈیکل آلات مینوفیکچرر اور YCDO SOP کے مطابق ہینڈل ہوں؛ سیفٹی لاک یا کیلیبریشن کنٹرول نہ ہٹائیں۔',
    'پیشہ ورانہ حفاظت، بشمول برقی اور ورکشاپ احتیاط، لازم ہے۔',
    'ایونٹ، ایمرجنسی یا مہم کی تفویض شدہ ڈیوٹی نہ چھوڑی جائے۔',
    'غیر مجاز غیر حاضری، غفلت یا حفاظتی خلاف ورزی پر YCDO قواعد کے مطابق ڈسپلنری کارروائی ہو سکتی ہے۔',
  ],
  SUPPORT_GRADE4: [
    'تفویض شدہ پوسٹ، جگہ، آلات اور سہولیات کی حفاظت کریں۔',
    'برانچ مینجمنٹ کی ڈیوٹی ایریا، شفٹ، صفائی اور نقل و حرکت کی ہدایات پر عمل کریں۔',
    'صفائی / سویپر کے فرائض حفظانِ صحت، ویسٹ اور انفیکشن کنٹرول SOP کے مطابق ہوں۔',
    'سیکیورٹی ڈیوٹی پر مقررہ پوسٹ پر رہیں، غیر مجاز داخلہ روکیں، اور واقعات فوری رپورٹ کریں۔',
    'لفٹ آپریٹر لفٹ سیفٹی طریقہ کار پر عمل کرے؛ اوورلوڈ یا استعمال کے دوران لفٹ چھوڑنا منع ہے۔',
    'لوڈر سامان صرف اجازت کے تحت منتقل کرے اور اسٹاک / آلات کو نقصان نہ پہنچائے۔',
    'ایونٹ، ایمرجنسی یا مہم کی تفویض شدہ ڈیوٹی نہ چھوڑی جائے۔',
    'غیر مجاز غیر حاضری، غفلت یا حفاظتی خلاف ورزی پر YCDO قواعد کے مطابق ڈسپلنری کارروائی ہو سکتی ہے۔',
  ],
  SUPPORT_OPERATIONS: [
    'تفویض شدہ جگہ، اوزار، آلات، اسٹاک اور سہولیات کی حفاظت کریں۔',
    'برانچ مینجمنٹ کی ڈیوٹی ایریا، شفٹ، صفائی اور نقل و حرکت کی ہدایات پر عمل کریں۔',
    'کچن عملہ حفظانِ صحت، ذخیرہ، تیاری، پیش کش اور فوڈ سیفٹی SOP پر عمل کرے۔',
    'کچن اسٹاک یا آلات کی کمی / نقصان فوری رپورٹ ہو۔',
    'صفائی کے فرائض حفظانِ صحت، ویسٹ اور انفیکشن کنٹرول SOP کے مطابق ہوں۔',
    'رائیڈر منظور شدہ راستے پر ہی سامان لے جائے، نمونوں / سپلائیز کی حفاظت کرے، اور مواد میں چھیڑ چھاڑ نہ کرے۔',
    'ایونٹ، ایمرجنسی یا مہم کی تفویض شدہ ڈیوٹی نہ چھوڑی جائے۔',
    'غیر مجاز غیر حاضری، غفلت یا حفاظتی خلاف ورزی پر YCDO قواعد کے مطابق ڈسپلنری کارروائی ہو سکتی ہے۔',
  ],
  VTI: [
    'تربیت یافتگان / طلبہ کے ساتھ پیشہ ورانہ اور عزت والا سلوک کیا جائے۔',
    'منظور شدہ نصاب، ٹائم ٹیبل، سبق اور عملی سرگرمی پر عمل ہو۔',
    'حاضری، ترقی اور تشخیص کا ریکارڈ درست رکھا جائے۔',
    'ہراساں کرنا، امتیاز اور نامناسب سلوک منع ہے۔',
    'تربیتی اوزار، مشینیں، سامان اور کاسمیٹکس محفوظ طریقے سے استعمال ہوں۔',
    'بیوٹیشن کی عملی تربیت حفظانِ صحت اور صفائی کے SOP کے مطابق ہو۔',
    'سلائی میں مشین، سوئی، کٹنگ اور برقی حفاظت کے اصول لاگو ہوں۔',
    'نظم، پابندیِ وقت اور صفائی کو فروغ دیا جائے۔',
    'پرنسپل / انچارج کی نگرانی میں کام ہو۔',
    'شکایت، حفاظتی مسئلہ، بدسلوکی اور آلات کا نقصان فوری رپورٹ ہو۔',
    'سرٹیفکیٹ، حاضری، تشخیص یا اسٹاک ریکارڈ میں چھیڑ چھاڑ منع ہے۔',
    'جب باضابطہ بلایا جائے تو VTI تقریبات، نمائشوں اور تربیتی پروگراموں میں شرکت لازم ہے۔',
    'تربیت یافتہ کے ڈیٹا کی رازداری قائم رکھیں۔',
    'ٹرانسفر یا علیحدگی پر درست ہینڈ اوور لازمی ہے۔',
    'بار بار غفلت، غیر حاضری، ریکارڈ میں چھیڑ چھاڑ یا SOP خلاف ورزی پر YCDO قواعد کے مطابق ڈسپلنری کارروائی ہو سکتی ہے۔',
  ],
};

export function appointmentSopHtml(
  templateCode: string,
  language: AppointmentLetterLanguage,
): string {
  const family = appointmentFamilyMeta(templateCode)?.sopFamily;
  if (!family) {
    throw new Error(
      `No department SOP family is configured for ${templateCode}.`,
    );
  }
  const clauses =
    language === AppointmentLetterLanguage.UR ? SOP_UR[family] : SOP_EN[family];
  return clauses.map((clause) => `<li>${clause}</li>`).join('');
}
