-- AlterEnum
ALTER TYPE "DeductionType" ADD VALUE IF NOT EXISTS 'MEDICINE_PENDING';
ALTER TYPE "DeductionType" ADD VALUE IF NOT EXISTS 'KITCHEN_PENDING';
ALTER TYPE "DeductionType" ADD VALUE IF NOT EXISTS 'LOAN';
ALTER TYPE "DeductionType" ADD VALUE IF NOT EXISTS 'ADVANCE';
ALTER TYPE "DeductionType" ADD VALUE IF NOT EXISTS 'ELECTRICITY_BILL';
ALTER TYPE "DeductionType" ADD VALUE IF NOT EXISTS 'MOBILE_BILL';
ALTER TYPE "DeductionType" ADD VALUE IF NOT EXISTS 'FINE';
