/**
 * READ-ONLY — full reconciliation of Dr Iram's (YCDO-2026-0383) August 2026
 * PayrollEntry: enumerate every PayrollDeduction row contributing to
 * totalDeductions, cross-reference each against AttendanceLog,
 * DisciplineEvent, and Letter, classify each as VALID / HISTORICAL_STALE_DATA
 * / CONFIRMED_BUG / DUPLICATE / INSUFFICIENT_EVIDENCE, and reconcile
 * SUM(deductions) against PayrollEntry.totalDeductions.
 *
 * Zero writes. Only reads Employee, StipendRecord, PayrollEntry,
 * PayrollDeduction, AttendanceLog, AuditLog, LeaveRecord, LeaveApproval,
 * Letter, DisciplineEvent.
 *
 * KNOWN DATA LIMITATIONS (reported, not worked around):
 *   - PayrollDeduction has NO timestamp column at all — the exact creation
 *     instant of any deduction cannot be read directly. Where the deduction
 *     was generated by discipline.helper.ts in the same transaction as a
 *     DisciplineEvent/Letter row, that row's createdAt/generatedAt is used
 *     as the closest available proxy and is labeled as such.
 *   - AttendanceLog has no updatedAt column — AuditLog(entity=AttendanceLog)
 *     is the only edit trail, and only for edits made through
 *     updateAttendance (full diff); markManual writes a mark-only entry with
 *     no diff, and biometric/raw-scan/reconcileShortLeaveAttendance writes
 *     leave no AuditLog entry at all. "Incident attendance later corrected"
 *     below is therefore a best-effort signal, not a guarantee of
 *     completeness.
 *
 * Run:
 *   DATABASE_URL="..." npx ts-node --transpile-only scripts/trace-dr-iram-payroll-deductions.ts > dr-iram-trace.json
 */

import {
  AttendanceLogType,
  AttendanceStatus,
  DeductionType,
  DisciplineCategory,
  PrismaClient,
} from '@prisma/client';

const prisma = new PrismaClient();

const EMPLOYEE_CODE = 'YCDO-2026-0383';
const TARGET_MONTH = 8;
const TARGET_YEAR = 2026;

const MONTH_START = new Date(Date.UTC(TARGET_YEAR, TARGET_MONTH - 1, 1, 0, 0, 0, 0));
const MONTH_END = new Date(Date.UTC(TARGET_YEAR, TARGET_MONTH - 1, 31, 23, 59, 59, 999));

function dateLabelOf(d: Date): string {
  return d.toISOString().slice(0, 10);
}

/** Every exact description template discipline.helper.ts is known to emit,
 * used to classify each row instead of guessing at free text. */
function classifyDescriptionTemplate(reason: DeductionType, description: string | null) {
  const desc = description ?? '';

  if (reason === DeductionType.LATE_ARRIVAL) {
    const m = desc.match(/^Late arrival deduction — monthly occurrence (\d+)$/);
    if (m) {
      return {
        templateMatched: 'LATE_ARRIVAL_MONTHLY_OCCURRENCE' as const,
        extractedOccurrence: Number(m[1]),
        extractedIncidentDate: null as string | null,
      };
    }
    return { templateMatched: 'UNRECOGNIZED' as const, extractedOccurrence: null, extractedIncidentDate: null };
  }

  if (reason === DeductionType.UNINFORMED_ABSENCE) {
    const dated1 = desc.match(/^Uninformed absence deduction \(2 days\) — (\d{4}-\d{2}-\d{2})$/);
    if (dated1) {
      return {
        templateMatched: 'UNINFORMED_ABSENT_DATED' as const,
        extractedOccurrence: null,
        extractedIncidentDate: dated1[1],
      };
    }
    const dated2 = desc.match(/^Absent without approved leave \(2 days stipend\) — (\d{4}-\d{2}-\d{2})$/);
    if (dated2) {
      return {
        templateMatched: 'ABSENT_DATED' as const,
        extractedOccurrence: null,
        extractedIncidentDate: dated2[1],
      };
    }
    // Legacy pre-date-suffix rows, or hand-entered adjustments.
    if (/^Uninformed absence deduction \(2 days\)$/.test(desc) || /^Absent without approved leave \(2 days stipend\)$/.test(desc)) {
      return { templateMatched: 'UNINFORMED_ABSENCE_LEGACY_UNDATED' as const, extractedOccurrence: null, extractedIncidentDate: null };
    }
    return { templateMatched: 'UNRECOGNIZED' as const, extractedOccurrence: null, extractedIncidentDate: null };
  }

  if (reason === DeductionType.DISCIPLINARY_FINE) {
    const m = desc.match(/^Missing checkout deduction — monthly occurrence (\d+)$/);
    if (m) {
      return {
        templateMatched: 'MISSING_CHECKOUT_MONTHLY_OCCURRENCE' as const,
        extractedOccurrence: Number(m[1]),
        extractedIncidentDate: null as string | null,
      };
    }
    return { templateMatched: 'UNRECOGNIZED' as const, extractedOccurrence: null, extractedIncidentDate: null };
  }

  if ((reason as string) === 'EXTRA_LEAVE_REJECTED') {
    const m = desc.match(/^Extra Full Leave rejected — 1-day deduction — (\d{4}-\d{2}-\d{2})$/);
    if (m) {
      return {
        templateMatched: 'EXTRA_LEAVE_REJECTED_DATED' as const,
        extractedOccurrence: null,
        extractedIncidentDate: m[1],
      };
    }
    return { templateMatched: 'UNRECOGNIZED' as const, extractedOccurrence: null, extractedIncidentDate: null };
  }

  if (reason === DeductionType.UNPAID_LEAVE) {
    return { templateMatched: 'UNPAID_LEAVE_AGGREGATE' as const, extractedOccurrence: null, extractedIncidentDate: null };
  }

  return { templateMatched: 'UNRECOGNIZED' as const, extractedOccurrence: null, extractedIncidentDate: null };
}

async function main() {
  console.error(`=== READ-ONLY TRACE: ${EMPLOYEE_CODE} August ${TARGET_YEAR} payroll deductions ===`);

  const employee = await prisma.employee.findUnique({
    where: { employeeCode: EMPLOYEE_CODE },
    select: {
      id: true,
      employeeCode: true,
      fullName: true,
      status: true,
      dutyStartTime: true,
      dutyEndTime: true,
      stipendRecords: { orderBy: { effectiveFrom: 'desc' } },
    },
  });

  if (!employee) {
    console.log(JSON.stringify({ found: false, employeeCode: EMPLOYEE_CODE }, null, 2));
    return;
  }

  // ── PayrollEntry for this employee/month/year (via any of their stipend
  // records — a mid-month rate change would still leave exactly one entry
  // per stipendRecordId/month/year, so search across all of them). ──
  const payrollEntries = await prisma.payrollEntry.findMany({
    where: {
      month: TARGET_MONTH,
      year: TARGET_YEAR,
      stipendRecord: { employeeId: employee.id },
    },
    include: { deductions: true },
  });

  // ── All August AttendanceLog rows ──
  const attendanceLogs = await prisma.attendanceLog.findMany({
    where: { employeeId: employee.id, date: { gte: MONTH_START, lte: MONTH_END } },
    orderBy: { date: 'asc' },
  });
  const attendanceByDate = new Map(
    attendanceLogs
      .filter((l) => l.type === AttendanceLogType.REGULAR)
      .map((l) => [dateLabelOf(l.date), l]),
  );
  const statusCounts: Record<string, number> = {};
  for (const l of attendanceLogs) {
    if (l.type !== AttendanceLogType.REGULAR) continue;
    statusCounts[l.status] = (statusCounts[l.status] ?? 0) + 1;
  }

  const attendanceLogIds = attendanceLogs.map((l) => l.id);
  const attendanceAuditLogs = attendanceLogIds.length
    ? await prisma.auditLog.findMany({
        where: { entity: 'AttendanceLog', entityId: { in: attendanceLogIds } },
        orderBy: { createdAt: 'asc' },
        select: { id: true, userId: true, action: true, entityId: true, changes: true, createdAt: true },
      })
    : [];
  const auditByLogId = new Map<string, typeof attendanceAuditLogs>();
  for (const a of attendanceAuditLogs) {
    const arr = auditByLogId.get(a.entityId) ?? [];
    arr.push(a);
    auditByLogId.set(a.entityId, arr);
  }
  const attendanceLogById = new Map(attendanceLogs.map((l) => [l.id, l]));

  // ── DisciplineEvent rows for August ──
  const disciplineEvents = await prisma.disciplineEvent.findMany({
    where: { employeeId: employee.id, incidentDate: { gte: MONTH_START, lte: MONTH_END } },
    orderBy: { createdAt: 'asc' },
  });
  const lateEvents = disciplineEvents.filter((e) => e.category === DisciplineCategory.LATE);
  const uaEvents = disciplineEvents.filter((e) => e.category === DisciplineCategory.UNINFORMED_ABSENT);
  function disciplineEventFor(category: DisciplineCategory, dateLabel: string | null) {
    if (!dateLabel) return null;
    return disciplineEvents.find((e) => e.category === category && dateLabelOf(e.incidentDate) === dateLabel) ?? null;
  }
  function disciplineEventForOccurrence(category: DisciplineCategory, occurrence: number | null) {
    if (occurrence == null) return null;
    return disciplineEvents.find((e) => e.category === category && e.occurrence === occurrence) ?? null;
  }

  // ── Letters for August ──
  const letters = await prisma.letter.findMany({
    where: { employeeId: employee.id, generatedAt: { gte: MONTH_START, lte: MONTH_END } },
    select: {
      id: true,
      letterNo: true,
      letterType: true,
      generatedAt: true,
      variables: true,
      acknowledgement: { select: { id: true, acknowledgedAt: true } },
    },
    orderBy: { generatedAt: 'asc' },
  });
  function letterForIncidentDate(dateLabel: string | null) {
    if (!dateLabel) return null;
    return (
      letters.find((l) => {
        const vars = l.variables as Record<string, unknown> | null;
        return vars && typeof vars === 'object' && (vars as any).incidentDate === dateLabel;
      }) ?? null
    );
  }
  function letterForOccurrence(occurrence: number | null, kind: 'late' | 'missingCheckout') {
    if (occurrence == null) return null;
    // occurrence-3/6 -> FINE letters carry fineAmount but not a numeric
    // occurrence field directly in variables; match via the same lateCount
    // used to build the deduction description, cross-referenced through the
    // DisciplineEvent row instead (safer than parsing Urdu prose).
    const ev =
      kind === 'late'
        ? disciplineEventForOccurrence(DisciplineCategory.LATE, occurrence)
        : disciplineEventForOccurrence(DisciplineCategory.MISSING_CHECKOUT, occurrence);
    if (!ev) return null;
    return letterForIncidentDate(dateLabelOf(ev.incidentDate));
  }

  // ── LeaveRecords overlapping August ──
  const leaveRecords = await prisma.leaveRecord.findMany({
    where: {
      employeeId: employee.id,
      OR: [{ startDate: { gte: MONTH_START, lte: MONTH_END } }, { endDate: { gte: MONTH_START, lte: MONTH_END } }],
    },
    include: { approvals: { orderBy: { actionAt: 'asc' } } },
    orderBy: { startDate: 'asc' },
  });

  // ── Build one detailed record per deduction ──
  type DeductionDetail = ReturnType<typeof buildDeductionDetail>;
  function buildDeductionDetail(
    d: (typeof payrollEntries)[number]['deductions'][number],
    payrollEntry: (typeof payrollEntries)[number],
  ) {
    const template = classifyDescriptionTemplate(d.reason, d.description);
    const incidentDate = template.extractedIncidentDate;
    const occurrence = template.extractedOccurrence;

    let matchedLog: ReturnType<typeof buildLogSummary> | null = null;
    let matchedDisciplineEvent: (typeof disciplineEvents)[number] | null = null;
    let matchedLetter: (typeof letters)[number] | null = null;

    if (incidentDate) {
      const log = attendanceByDate.get(incidentDate) ?? null;
      matchedLog = log ? buildLogSummary(log) : null;
      matchedLetter = letterForIncidentDate(incidentDate);
      if (template.templateMatched === 'UNINFORMED_ABSENT_DATED' || template.templateMatched === 'ABSENT_DATED') {
        matchedDisciplineEvent = disciplineEventFor(DisciplineCategory.UNINFORMED_ABSENT, incidentDate);
      }
    } else if (occurrence != null) {
      if (template.templateMatched === 'LATE_ARRIVAL_MONTHLY_OCCURRENCE') {
        matchedDisciplineEvent = disciplineEventForOccurrence(DisciplineCategory.LATE, occurrence);
        matchedLetter = letterForOccurrence(occurrence, 'late');
      } else if (template.templateMatched === 'MISSING_CHECKOUT_MONTHLY_OCCURRENCE') {
        matchedDisciplineEvent = disciplineEventForOccurrence(DisciplineCategory.MISSING_CHECKOUT, occurrence);
        matchedLetter = letterForOccurrence(occurrence, 'missingCheckout');
      }
      if (matchedDisciplineEvent) {
        const dl = dateLabelOf(matchedDisciplineEvent.incidentDate);
        const log = attendanceByDate.get(dl) ?? null;
        matchedLog = log ? buildLogSummary(log) : null;
      }
    }

    // Was the matched attendance row edited after the deduction's
    // best-effort creation-time proxy (DisciplineEvent.createdAt /
    // Letter.generatedAt)? Best-effort only — see file header.
    const creationProxy = matchedDisciplineEvent?.createdAt ?? matchedLetter?.generatedAt ?? null;
    let correctedAfterIncident: boolean | 'UNKNOWN_NO_TIMESTAMP_PROXY' = 'UNKNOWN_NO_TIMESTAMP_PROXY';
    if (matchedLog && creationProxy) {
      const auditsForLog = auditByLogId.get(matchedLog.id) ?? [];
      correctedAfterIncident = auditsForLog.some((a) => a.createdAt > creationProxy);
    } else if (matchedLog) {
      correctedAfterIncident = false;
    }

    // Evidence-based verdict inputs.
    const currentStatus = matchedLog?.status ?? null;
    let currentEvidenceSupportsDeduction = false;
    if (template.templateMatched === 'LATE_ARRIVAL_MONTHLY_OCCURRENCE') {
      currentEvidenceSupportsDeduction =
        !!matchedDisciplineEvent &&
        (matchedDisciplineEvent.occurrence === 3 || matchedDisciplineEvent.occurrence === 6) &&
        (currentStatus === AttendanceStatus.LATE || currentStatus === AttendanceStatus.HALF_DAY);
    } else if (template.templateMatched === 'UNINFORMED_ABSENT_DATED') {
      currentEvidenceSupportsDeduction = currentStatus === AttendanceStatus.UNINFORMED_ABSENT && !!matchedDisciplineEvent;
    } else if (template.templateMatched === 'ABSENT_DATED') {
      currentEvidenceSupportsDeduction = currentStatus === AttendanceStatus.ABSENT;
    } else if (template.templateMatched === 'MISSING_CHECKOUT_MONTHLY_OCCURRENCE') {
      currentEvidenceSupportsDeduction =
        !!matchedDisciplineEvent && !!matchedLog && matchedLog.checkIn != null && matchedLog.checkOut == null;
    }

    return {
      deductionId: d.id,
      category: d.reason,
      amount: Number(d.amount),
      description: d.description,
      payrollEntryId: payrollEntry.id,
      employeeId: employee!.id,
      employeeCode: employee!.employeeCode,
      employeeName: employee!.fullName,
      payrollStatus: payrollEntry.status,
      descriptionTemplate: template.templateMatched,
      extractedIncidentDate: incidentDate,
      extractedLateOccurrence: template.templateMatched === 'LATE_ARRIVAL_MONTHLY_OCCURRENCE' ? occurrence : null,
      extractedOccurrence: occurrence,
      matchingAttendanceLog: matchedLog,
      currentAttendanceLogStatus: currentStatus,
      matchingDisciplineEvent: matchedDisciplineEvent
        ? {
            id: matchedDisciplineEvent.id,
            category: matchedDisciplineEvent.category,
            incidentDate: dateLabelOf(matchedDisciplineEvent.incidentDate),
            occurrence: matchedDisciplineEvent.occurrence,
            createdAt: matchedDisciplineEvent.createdAt.toISOString(),
          }
        : null,
      matchingLetter: matchedLetter
        ? {
            id: matchedLetter.id,
            letterNo: matchedLetter.letterNo,
            letterType: matchedLetter.letterType,
            generatedAt: matchedLetter.generatedAt.toISOString(),
            variables: matchedLetter.variables,
            acknowledged: !!matchedLetter.acknowledgement,
          }
        : null,
      creationTimeProxy: creationProxy ? creationProxy.toISOString() : null,
      correctedAfterIncident,
      currentEvidenceSupportsDeduction,
    };
  }

  function buildLogSummary(log: (typeof attendanceLogs)[number]) {
    return {
      id: log.id,
      date: dateLabelOf(log.date),
      type: log.type,
      status: log.status,
      lateMinutes: log.lateMinutes,
      checkIn: log.checkIn ? log.checkIn.toISOString() : null,
      checkOut: log.checkOut ? log.checkOut.toISOString() : null,
      note: log.note,
      source: log.source,
    };
  }

  const allDeductionDetails: DeductionDetail[] = [];
  for (const pe of payrollEntries) {
    for (const d of pe.deductions) {
      allDeductionDetails.push(buildDeductionDetail(d, pe));
    }
  }

  // ── Duplicate detection: identical (reason, description) pairs within the
  // same payrollEntry can only legitimately exist once each — the create
  // paths for LATE_ARRIVAL/DISCIPLINARY_FINE check `alreadyDeducted` before
  // inserting, and UNINFORMED_ABSENT/MISSING_CHECKOUT are additionally
  // gated by claimDisciplineEvent. Two rows with the same (payrollEntryId,
  // reason, description) can only mean the guard was bypassed or the row
  // predates the guard. ──
  const dupKey = (d: DeductionDetail) => `${d.payrollEntryId}::${d.category}::${d.description}`;
  const dupCounts = new Map<string, number>();
  for (const d of allDeductionDetails) {
    dupCounts.set(dupKey(d), (dupCounts.get(dupKey(d)) ?? 0) + 1);
  }

  // ── Classification ──
  function classify(d: DeductionDetail): 'VALID' | 'HISTORICAL_STALE_DATA' | 'CONFIRMED_BUG' | 'DUPLICATE' | 'INSUFFICIENT_EVIDENCE' {
    if ((dupCounts.get(dupKey(d)) ?? 0) > 1) return 'DUPLICATE';

    if (d.descriptionTemplate === 'UNINFORMED_ABSENCE_LEGACY_UNDATED') return 'HISTORICAL_STALE_DATA';

    if (d.descriptionTemplate === 'LATE_ARRIVAL_MONTHLY_OCCURRENCE') {
      // occurrence 9 should never carry a deduction — 9th is suspension-only.
      if (d.extractedLateOccurrence === 9) return 'CONFIRMED_BUG';
      if (d.extractedLateOccurrence !== 3 && d.extractedLateOccurrence !== 6) return 'CONFIRMED_BUG';
      if (!d.matchingDisciplineEvent) return 'INSUFFICIENT_EVIDENCE';
      if (d.currentEvidenceSupportsDeduction) return 'VALID';
      if (d.correctedAfterIncident === true) return 'HISTORICAL_STALE_DATA';
      return 'INSUFFICIENT_EVIDENCE';
    }

    if (d.descriptionTemplate === 'UNINFORMED_ABSENT_DATED') {
      if (!d.matchingAttendanceLog) return 'INSUFFICIENT_EVIDENCE';
      if (d.currentEvidenceSupportsDeduction) return 'VALID';
      if (d.correctedAfterIncident === true) return 'HISTORICAL_STALE_DATA';
      if (d.currentAttendanceLogStatus !== AttendanceStatus.UNINFORMED_ABSENT) return 'HISTORICAL_STALE_DATA';
      return 'INSUFFICIENT_EVIDENCE';
    }

    if (d.descriptionTemplate === 'ABSENT_DATED') {
      if (!d.matchingAttendanceLog) return 'INSUFFICIENT_EVIDENCE';
      if (d.currentEvidenceSupportsDeduction) return 'VALID';
      if (d.correctedAfterIncident === true) return 'HISTORICAL_STALE_DATA';
      if (d.currentAttendanceLogStatus !== AttendanceStatus.ABSENT) return 'HISTORICAL_STALE_DATA';
      return 'INSUFFICIENT_EVIDENCE';
    }

    if (d.descriptionTemplate === 'MISSING_CHECKOUT_MONTHLY_OCCURRENCE') {
      if (!d.matchingDisciplineEvent) return 'INSUFFICIENT_EVIDENCE';
      if (d.currentEvidenceSupportsDeduction) return 'VALID';
      if (d.correctedAfterIncident === true) return 'HISTORICAL_STALE_DATA';
      return 'INSUFFICIENT_EVIDENCE';
    }

    if (d.descriptionTemplate === 'EXTRA_LEAVE_REJECTED_DATED' || d.descriptionTemplate === 'UNPAID_LEAVE_AGGREGATE') {
      // Not modeled by discipline.helper.ts's reversal logic and not part
      // of this investigation's named suspects — reported, not judged.
      return 'INSUFFICIENT_EVIDENCE';
    }

    return 'INSUFFICIENT_EVIDENCE';
  }

  const classifiedDeductions = allDeductionDetails.map((d) => ({ ...d, verdict: classify(d) }));

  // ── Specific checks requested ──

  // 1. 2026-08-17 1-minute LATE — should be occurrence 1 / Advice only, no fine.
  const aug17 = attendanceByDate.get('2026-08-17') ?? null;
  const aug17DisciplineEvent = disciplineEventFor(DisciplineCategory.LATE, '2026-08-17');
  const aug17Letter = letterForIncidentDate('2026-08-17');
  const aug17FineDeductionsFound = classifiedDeductions.filter(
    (d) => d.extractedIncidentDate === '2026-08-17' || (d.matchingDisciplineEvent && d.matchingDisciplineEvent.incidentDate === '2026-08-17'),
  );
  const check1_aug17OneMinuteLate = {
    attendanceLog: aug17 ? buildLogSummary(aug17) : null,
    disciplineEvent: aug17DisciplineEvent
      ? {
          id: aug17DisciplineEvent.id,
          occurrence: aug17DisciplineEvent.occurrence,
          category: aug17DisciplineEvent.category,
        }
      : null,
    letter: aug17Letter ? { id: aug17Letter.id, letterType: aug17Letter.letterType, letterNo: aug17Letter.letterNo } : null,
    fineDeductionsMatchedToThisDate: aug17FineDeductionsFound.map((d) => d.deductionId),
    expectedOccurrence1AdviceOnlyNoFine:
      !!aug17DisciplineEvent &&
      aug17DisciplineEvent.occurrence === 1 &&
      (!aug17Letter || aug17Letter.letterType === 'ADVICE') &&
      aug17FineDeductionsFound.length === 0,
  };

  // 2. 2026-08-05 — ABSENT vs UNINFORMED_ABSENT, was a 2-day deduction generated?
  const aug05 = attendanceByDate.get('2026-08-05') ?? null;
  const aug05UaEvent = disciplineEventFor(DisciplineCategory.UNINFORMED_ABSENT, '2026-08-05');
  const aug05Deductions = classifiedDeductions.filter((d) => d.extractedIncidentDate === '2026-08-05');
  const check2_aug05 = {
    currentAttendanceLog: aug05 ? buildLogSummary(aug05) : null,
    currentStatus: aug05?.status ?? null,
    uninformedAbsentDisciplineEvent: aug05UaEvent
      ? { id: aug05UaEvent.id, occurrence: aug05UaEvent.occurrence, createdAt: aug05UaEvent.createdAt.toISOString() }
      : null,
    twoDayDeductionsFoundForThisDate: aug05Deductions.map((d) => ({
      deductionId: d.deductionId,
      description: d.description,
      amount: d.amount,
      template: d.descriptionTemplate,
      verdict: d.verdict,
    })),
    note:
      'applyAbsentDeduction (ABSENT status path) has NO claimDisciplineEvent idempotency gate and NO alreadyDeducted check — unlike applyUninformedAbsentDeduction (UNINFORMED_ABSENT path). If this date was ever re-processed through the ABSENT path more than once, duplicate "Absent without approved leave" rows are structurally possible with nothing in discipline.helper.ts to prevent it.',
  };

  // 3. Legacy undated uninformed-absence deductions.
  const check3_legacyUndated = classifiedDeductions.filter((d) => d.descriptionTemplate === 'UNINFORMED_ABSENCE_LEGACY_UNDATED');

  // 4. Occurrence-9 LATE deductions (should never exist — 9th is suspension-only).
  const check4_occurrence9Late = classifiedDeductions.filter(
    (d) => d.descriptionTemplate === 'LATE_ARRIVAL_MONTHLY_OCCURRENCE' && d.extractedLateOccurrence === 9,
  );

  // 5. Deductions whose incident attendance was later corrected.
  const check5_correctedAfterIncident = classifiedDeductions.filter((d) => d.correctedAfterIncident === true);

  // 6. Duplicate deduction rows.
  const check6_duplicates = classifiedDeductions.filter((d) => d.verdict === 'DUPLICATE');

  // ── Reconciliation ──
  const reconciliations = payrollEntries.map((pe) => {
    const rows = classifiedDeductions.filter((d) => d.payrollEntryId === pe.id);
    const sumOfRows = rows.reduce((acc, d) => acc + d.amount, 0);
    const validTotal = rows.filter((d) => d.verdict === 'VALID').reduce((acc, d) => acc + d.amount, 0);
    const invalidTotal = rows.filter((d) => d.verdict !== 'VALID').reduce((acc, d) => acc + d.amount, 0);
    const storedTotalDeductions = Number(pe.totalDeductions);
    const storedNetStipend = Number(pe.netStipend);
    const storedBasic = Number(pe.basicStipend);
    return {
      payrollEntryId: pe.id,
      status: pe.status,
      basicStipend: storedBasic,
      storedTotalDeductions,
      storedNetStipend,
      sumOfAllDeductionRows: Number(sumOfRows.toFixed(2)),
      sumMatchesStoredTotalDeductions: Math.abs(sumOfRows - storedTotalDeductions) < 0.01,
      deductionCount: rows.length,
      verdictBreakdown: rows.reduce<Record<string, number>>((acc, d) => {
        acc[d.verdict] = (acc[d.verdict] ?? 0) + 1;
        return acc;
      }, {}),
      expectedValidDeductionsTotal: Number(validTotal.toFixed(2)),
      invalidOrStaleDeductionsTotal: Number(invalidTotal.toFixed(2)),
      currentPayrollTotalDeductions: storedTotalDeductions,
      correctedExpectedTotalDeductions: Number(validTotal.toFixed(2)),
      correctedExpectedNetStipend: Number((storedBasic - validTotal).toFixed(2)),
    };
  });

  const finalTable = classifiedDeductions.map((d) => ({
    deductionId: d.deductionId,
    amount: d.amount,
    incident: d.extractedIncidentDate ?? d.matchingDisciplineEvent?.incidentDate ?? d.description,
    currentEvidence: d.currentEvidenceSupportsDeduction
      ? `SUPPORTS (status=${d.currentAttendanceLogStatus ?? 'n/a'})`
      : `DOES NOT SUPPORT (status=${d.currentAttendanceLogStatus ?? 'no matching log'}, correctedAfterIncident=${d.correctedAfterIncident})`,
    verdict: d.verdict,
  }));

  const report = {
    generatedAt: new Date().toISOString(),
    readOnly: true,
    employee: {
      id: employee.id,
      employeeCode: employee.employeeCode,
      fullName: employee.fullName,
      status: employee.status,
    },
    attendanceStatusCountsThisMonth: statusCounts,
    payrollEntriesFound: payrollEntries.length,
    allDeductions: classifiedDeductions,
    reconciliation: reconciliations,
    finalTable,
    checks: {
      check1_aug17OneMinuteLateOccurrence1AdviceOnlyNoFine: check1_aug17OneMinuteLate,
      check2_aug05AbsentVsUninformedAbsent: check2_aug05,
      check3_legacyUndatedUninformedAbsenceDeductions: check3_legacyUndated.map((d) => d.deductionId),
      check4_occurrence9LateDeductions: check4_occurrence9Late.map((d) => d.deductionId),
      check5_deductionsWithIncidentAttendanceLaterCorrected: check5_correctedAfterIncident.map((d) => d.deductionId),
      check6_duplicateDeductionRows: check6_duplicates.map((d) => d.deductionId),
    },
    dataLimitations: [
      'PayrollDeduction has no createdAt/updatedAt column — exact creation instant not directly queryable; DisciplineEvent.createdAt / Letter.generatedAt used as same-transaction proxies where a match exists.',
      'AttendanceLog has no updatedAt column — correctedAfterIncident is derived only from AuditLog(entity=AttendanceLog), which is incomplete for markManual/biometric/reconcileShortLeaveAttendance edits (see file header).',
    ],
  };

  console.log(JSON.stringify(report, null, 2));
  console.error('=== DONE (read-only — no data was modified) ===');
}

main()
  .catch((err) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
